export  const CONSTANTS = { 
     PRINT_NOT:"PRINT_STATEMENTS_ARE_NOT_ALLOWED",
     NO_CHANGE_DECLARATION:"DONT_CHANGE_THE_DEFAULT_METHOD_DECLARATION",
     DECLARATION_MISSING:"METHOD_DECLARATION_MISSING",
     DATA_TYPE_MODIFIED:"DATA_TYPES_DECLARATION_MODIFIED"
}